# Assignment 1+2
try:
    a = 1/0
except ZeroDivisionError as e:
    print('Divided by zero!')

# Assignment 3:
# Yes, this code is legal!

# Assignment 4:
# The except can handle all the exceptions..

# Assignment 5:
# You can't catch serious bugs and that can be a real problem at the future

# Assignment 6:
# except IOError - It is an error raised when an input/output operation fails, such as the print statement or the open() function
# except ZeroDivisionError - It is an error raised when an division by zero appears

